
default: matrix
matrix:
	g++ -g matrix_test.cpp ../src/matrix.cpp test.cpp ../src/vector3.cpp -I../include/
vector:
	g++ -g vector_test.cpp test.cpp ../src/quaternion.cpp ../src/vector3.cpp -I../include/
